mode: development
media_root: media
deploy_root: ../tipiirai.github.com

media_url: /media
base_url: http://cloudpanic.com/
template: hyde.ext.jinja2
meta:
    extends: story.j2
    twitter: http://twitter.com/cloudpanic
    analytics: UA-19863497-1
    keywords: "IT trends, technology trends, computing trends, cloud trends, cloud technologies, sap sucks"
    time: !!timestamp '2000-01-01 10:00:00'
    group: None
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.folders.FlattenerPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.grouper.GrouperPlugin
less:
    app: /usr/bin/less
sorter:
    time:
        attr:
            - meta.time
        reverse: True
        filters:
            source_file.kind: html
            meta.listable: True
grouper:
    cloudpanic:
        sorter: time
        groups:
            -
                name: cloud
            -
                name: panic
publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../tipiirai.github.com
        url: git@github.com:tipiirai/tipiirai.github.com.git
        branch: master
flattener:
    items:
        -
            source: tech
            target: ''
        -
            source: crap
            target: ''
